In [1]:
import pandas as pd
import numpy as np

file_path = 'C:\\Users\\Andrea\\Documents\\DATA\\Mid-bootcamp project\\Exploratory\\performance_f.csv'
data1 = pd.read_csv(file_path)
file_path = 'C:\\Users\\Andrea\\Documents\\DATA\\Mid-bootcamp project\\Exploratory\\performance_g.csv'
data2 = pd.read_csv(file_path)
file_path = 'C:\\Users\\Andrea\\Documents\\DATA\\Mid-bootcamp project\\Exploratory\\performance_i.csv'
data3 = pd.read_csv(file_path)

In [2]:
data1.T

                               0
total_impressions_f   4233999.00
total_clicks_f         370227.00
ctr_f                       8.74
total_interactions_f   963191.00
total_investment_f      72434.00
Cost_impression_f          58.45
Cost_clicks_f               5.11
Cost_interactions_f        13.29
ROI_f                     433.98

In [3]:
data2.T

                               0
total_impressions_g   9948189.00
total_clicks_g        1752919.00
ctr_g                      17.62
total_interactions_g  1024895.00
total_spent_g          149355.00
Cost_impression_f          66.60
Cost_clicks_f              11.73
Cost_interactions_f         6.86
ROI_g                     121.86

In [4]:
data3.T

                               0
total_impressions_i   4215066.00
total_clicks_i         336223.00
ctr_i                       7.98
total_interactions_i   818786.00
total_investment_i      86429.00
Cost_impression_i          48.77
Cost_clicks_i               3.89
Cost_interactions_i         9.47
ROI_i                     408.70

In [5]:
performance = pd.concat([data1, data2, data3], axis=1)
performance.T

                               0
total_impressions_f   4233999.00
total_clicks_f         370227.00
ctr_f                       8.74
total_interactions_f   963191.00
total_investment_f      72434.00
Cost_impression_f          58.45
Cost_clicks_f               5.11
Cost_interactions_f        13.29
ROI_f                     433.98
total_impressions_g   9948189.00
total_clicks_g        1752919.00
ctr_g                      17.62
total_interactions_g  1024895.00
total_spent_g          149355.00
Cost_impression_f          66.60
Cost_clicks_f              11.73
Cost_interactions_f         6.86
ROI_g                     121.86
total_impressions_i   4215066.00
total_clicks_i         336223.00
ctr_i                       7.98
total_interactions_i   818786.00
total_investment_i      86429.00
Cost_impression_i          48.77
Cost_clicks_i               3.89
Cost_interactions_i         9.47
ROI_i                     408.70

In [6]:
performance.dtypes

total_impressions_f       int64
total_clicks_f            int64
ctr_f                   float64
total_interactions_f      int64
total_investment_f        int64
Cost_impression_f       float64
Cost_clicks_f           float64
Cost_interactions_f     float64
ROI_f                   float64
total_impressions_g       int64
total_clicks_g            int64
ctr_g                   float64
total_interactions_g      int64
total_spent_g             int64
Cost_impression_f       float64
Cost_clicks_f           float64
Cost_interactions_f     float64
ROI_g                   float64
total_impressions_i       int64
total_clicks_i            int64
ctr_i                   float64
total_interactions_i      int64
total_investment_i        int64
Cost_impression_i       float64
Cost_clicks_i           float64
Cost_interactions_i     float64
ROI_i                   float64
dtype: object

In [10]:
performance = pd.DataFrame({
    'Category': ['f', 'g', 'i'],
    'total_impressions': [4233999.00, 9948189.00, 4215066.00],
    'total_clicks': [370227.00, 1752919.00, 336223.00],
    'ctr': [8.74, 17.62, 7.98],
    'total_interactions': [963191.00, 1024895.00, 818786.00],
    'total_investment': [72434.00, 149355.00, 86429.00],
    'cost_impression': [58.45, 66.60, 48.77],
    'cost_clicks': [5.11, 11.73, 3.89],
    'cost_interactions': [13.29, 6.86, 9.47],
    'ROI': [433.98, 121.86, 408.70]
})

In [11]:
performance.dtypes

Category               object
total_impressions     float64
total_clicks          float64
ctr                   float64
total_interactions    float64
total_investment      float64
cost_impression       float64
cost_clicks           float64
cost_interactions     float64
ROI                   float64
dtype: object

In [13]:
performance['total_impressions'] = performance['total_impressions'].astype(int)
performance['total_clicks'] = performance['total_clicks'].astype(int)
performance['ctr'] = performance['ctr'].astype(int)
performance['total_interactions'] = performance['total_interactions'].astype(int)
performance['total_investment'] = performance['total_investment'].astype(int)
performance['cost_impression'] = performance['cost_impression'].astype(int)
performance['cost_clicks'] = performance['cost_clicks'].astype(int)
performance['cost_interactions'] = performance['cost_interactions'].astype(int)
performance['ROI'] = performance['ROI'].astype(int)

In [14]:
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(data) 
X_train_scaled_arr = transformer.transform(data)
X_train_scaled = pd.DataFrame(X_train_scaled_arr, columns=data.columns)
X_train_scaled.T

ValueError: could not convert string to float: 'f'

In [ ]:
performance['total_impressions'] = performance['total_impressions'].astype(int)
performance['total_clicks'] = performance['total_clicks'].astype(int)
performance['ctr'] = performance['ctr'].astype(int)
performance['total_interactions'] = performance['total_interactions'].astype(int)
performance['total_investment'] = performance['total_investment'].astype(int)
performance['cost_impression'] = performance['cost_impression'].astype(int)
performance['cost_clicks'] = performance['cost_clicks'].astype(int)
performance['cost_interactions'] = performance['cost_interactions'].astype(int)
performance['roi'] = performance['roi'].astype(int)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(X_train_num) 
X_train_scaled_arr = transformer.transform(X_train_num)
X_train_scaled = pd.DataFrame(X_train_scaled_arr, columns=X_train_num.columns)
X_train_scaled.head()

In [ ]:
def get_best_category(total_impressions_f, total_impressions_g, total_impressions_i):
    if total_impressions_f > total_impressions_i:
        if total_impressions_f > total_impressions_g:
            return total_impressions_f
        else:
            return total_impressions_g
    elif total_impressions_i > total_impressions_g:
        return total_impressions_i
    else:
        return total_impressions_g

best_category_impressions = get_best_category(total_impressions_f, total_impressions_g, total_impressions_i)
print("La mejor categoría en función de las impresiones totales es:", best_category_impressions)

In [ ]:
segments = ['f', 'g', 'i']
best_performance = None

for segment in segments:
    impressions_column = f'total_impressions_{segment}'
    impressions = performance[impressions_column].iloc[0]
    
    if best_performance is None or impressions > performance[f'total_impressions_{best_performance}'].iloc[0]:
        best_performance = segment

print("Best performance in total_impressions_",best_performance)

In [ ]:
def get_best_category(total_impressions_f, total_impressions_g, total_impressions_i):
    if total_impressions_f > total_impressions_i:
        if total_impressions_f > total_impressions_g:
            return total_impressions_f
        else:
            return total_impressions_g
    elif total_impressions_i > total_impressions_g:
        return total_impressions_i
    else:
        return total_impressions_g

best_category_impressions = get_best_category(total_impressions_f, total_impressions_g, total_impressions_i)
print("La mejor categoría en función de las impresiones totales es:", best_category_impressions)

In [ ]:
import pandas as pd

# Create a DataFrame with the performance data
data = {
    'category': ['f', 'g', 'i'],
    'total_impressions': [4233999.00, 9948189.00, 4215066.00],
    'total_clicks': [370227.00, 1752919.00, 336223.00],
    'ctr': [8.74, 17.62, 7.98],
    'total_interactions': [963191.00, 1024895.00, 818786.00],
    'total_investment': [72434.00, 0.00, 86429.00],
    'cost_impression': [58.45, 66.60, 48.77],
    'cost_clicks': [5.11, 11.73, 3.89],
    'cost_interactions': [13.29, 6.86, 9.47],
    'roi': [433.98, 121.86, 408.70]
}

performance = pd.DataFrame(data)

performance['total_impressions'] = performance['total_impressions'].astype(int)
performance['total_clicks'] = performance['total_clicks'].astype(int)
performance['ctr'] = performance['ctr'].astype(int)
performance['total_interactions'] = performance['total_interactions'].astype(int)
performance['total_investment'] = performance['total_investment'].astype(int)
performance['cost_impression'] = performance['cost_impression'].astype(int)
performance['cost_clicks'] = performance['cost_clicks'].astype(int)
performance['cost_interactions'] = performance['cost_interactions'].astype(int)
performance['roi'] = performance['roi'].astype(int)

# Define weights for each metric
weights = {
    'total_impressions': 0.2,
    'total_clicks': 0.2,
    'ctr': 0.3,
    'total_interactions': 0.2,
    'total_investment': -0.2,
    'cost_impression': -0.05,
    'cost_clicks': -0.05,
    'cost_interactions': -0.05,
    'roi': 0.3
}

# Calculate the performance score for each category
performance['score'] = (performance[list(weights.keys())] * list(weights.values())).sum(axis=1)

# Find the category with the highest performance score
best_category = performance['category'].iloc[performance['score'].idxmax()]

print("Best performing category:", best_category)

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Crear el dataframe con los datos de rendimiento
data = pd.DataFrame({
    'Category': ['f', 'g', 'i'],
    'total_impressions': [4233999.00, 9948189.00, 4215066.00],
    'total_clicks': [370227.00, 1752919.00, 336223.00],
    'ctr': [8.74, 17.62, 7.98],
    'total_interactions': [963191.00, 1024895.00, 818786.00],
    'total_investment': [72434.00, 149355.00, 86429.00],
    'cost_impression': [58.45, 66.60, 48.77],
    'cost_clicks': [5.11, 11.73, 3.89],
    'cost_interactions': [13.29, 6.86, 9.47],
    'ROI': [433.98, 121.86, 408.70]
})

# Separar las variables de entrada (X) y la variable objetivo (y)
X = data.drop(['Category'], axis=1)
y = data['Category']

# Crear y entrenar el modelo de clasificación Random Forest
model = RandomForestClassifier()
model.fit(X, y)

# Realizar predicciones para determinar la mejor categoría
predicted_category = model.predict(X)
best_category = predicted_category[0]

print("La mejor categoría es:", best_category)

In [ ]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

# Crear el dataframe con los datos de rendimiento
data = pd.DataFrame({
    'Category': ['f', 'g', 'i'],
    'total_impressions': [4233999.00, 9948189.00, 4215066.00],
    'total_clicks': [370227.00, 1752919.00, 336223.00],
    'ctr': [8.74, 17.62, 7.98],
    'total_interactions': [963191.00, 1024895.00, 818786.00],
    'total_investment': [72434.00, 149355.00, 86429.00],
    'cost_impression': [58.45, 66.60, 48.77],
    'cost_clicks': [5.11, 11.73, 3.89],
    'cost_interactions': [13.29, 6.86, 9.47],
    'ROI': [433.98, 121.86, 408.70]
})

# Separar las variables de entrada (X) y la variable objetivo (y)
X = data.drop(['Category'], axis=1)
y = data['Category']

# Crear y entrenar el modelo de clasificación KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X, y)

# Realizar predicciones para determinar la mejor categoría
predicted_category = model.predict(X)
best_category = predicted_category[0]

print("La mejor categoría es:", best_category)